# Generated by Django 5.0.7 on 2024-11-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('GPay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Card', 'Card')], default='COD', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
